// Generated by Flexc++ V2.06.02 on Fri, 16 Mar 2018 22:43:53 +0100

#ifndef Scanner_H_INCLUDED_
#define Scanner_H_INCLUDED_

// $insert baseclass_h
#include "Scannerbase.h"


// $insert classHead
class Scanner: public ScannerBase
{
    private:
        std::shared_ptr<std::ostream> d_stringlist;
        size_t d_stringLine;

    public:
        enum Tokens
        {
            STRING = 0x100,
            OTHER
        };

        void printToStringlist();   //prints to the list of strings
        void printGetMsg(size_t lineNumb);
                              //prints getter message to the new file
        void printToFile();   //print other characters to new file
        void setStringList(); //sets d_stringlist to the appropriate directory
                              //and sets d_stringLine to zero;

        //scanners standard functions
        explicit Scanner(std::istream &in = std::cin,
                                std::ostream &out = std::cout);

        Scanner(std::string const &infile, std::string const &outfile);

        // $insert lexFunctionDecl
        int lex();

    private:
        int lex__();
        int executeAction__(size_t ruleNr);

        void print();
        void preCode();     // re-implement this function for code that must
                            // be exec'ed before the patternmatching starts

        void postCode(PostEnum__ type);
                            // re-implement this function for code that must
                            // be exec'ed after the rules's actions.
};

// $insert scannerConstructors
inline Scanner::Scanner(std::istream &in, std::ostream &out)
:
    ScannerBase(in, out)
{}

inline Scanner::Scanner(std::string const &infile, std::string const &outfile)
:
    ScannerBase(infile, outfile)
{}

// $insert inlineLexFunction
inline int Scanner::lex()
{
    return lex__();
}

inline void Scanner::preCode()
{
    // optionally replace by your own code
}

inline void Scanner::postCode(PostEnum__ type)
{
    // optionally replace by your own code
}

inline void Scanner::print()
{
    print__();
}


#endif // Scanner_H_INCLUDED_
